# Numpy & Pandas - GDSC NTNU
> GDSC NTNU<br>
> 講者：Hugo

>[Numpy](#Numpy)<br>
>[Pandas](#Pandas)<br>
>[I/O: Input and Output](#Input/Output-(I/O))

# Numpy
> Numpy 簡介<br>
> Numpy Array 的基本操作<br>
> Numpy Array 的合併與切割<br>
> Numpy Array 的運算<br>
> Numpy Array 的屬性<br>
> Numpy Array 資料讀寫

### Numpy 簡介
 - 資料科學和機器學習常用的資料結構
 - 裝載相同類型資料的多維陣列
 - 較 List 高效且擁有多項功能，使用上須注意與 List 的差異
 - shape：資料維度, ex. (2,3) 代表 2x3 的矩陣
 - dtype：資料型態, 陣列中元素的型態
 - 使用前須先導入 numpy 函式庫

導入 Numpy 函式庫

In [1]:
import numpy as np

### Numpy Array 的基本操作
> 建立 Numpy Array<br>
> 取得 Numpy Array 的值<br>
> 修改 Numpy Array 的值<br>
> 新增 Numpy Array 的值<br>
> 刪除 Numpy Array 的值

#### 建立 Numpy Array

使用 List 建立 Array => np.array ( List )

In [2]:
# 一維 Array
one_dim = np.array([1, 2, 3])
one_dim
# array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# 二維 Array
two_dim = 
two_dim
# array([[1, 2, 3],
#        [4, 5, 6]])

In [3]:
# 三維 Array
three_dim = np.array([[[1,2,3],[4,5,6]],[7,8,9],[9,8,7]])
three_dim
# array([[[1, 2, 3],
#         [4, 5, 6]],
# 
#        [[7, 8, 9],
#         [9, 8, 7]]])

C:\Users\user\AppData\Local\Temp\ipykernel_7092\4214628559.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  three_dim = np.array([[[1,2,3],[4,5,6]],[7,8,9],[9,8,7]])


array([list([[1, 2, 3], [4, 5, 6]]), list([7, 8, 9]), list([9, 8, 7])],
      dtype=object)

建立全為 0 的 Array => np.zeros ( shape )

In [ ]:
zero_array = 
zero_array
# array([[0., 0., 0.],
#        [0., 0., 0.]])

建立全為 1 的 Array => np.ones ( shape )

In [ ]:
# 試試看建立成三維
one_array = 
one_array

建立指定數值的 Array => np.full ( shape, number )

In [ ]:
# try int
eight_array = 
eight_array

In [ ]:
# try float
one_array = 
one_array

建立有序數列的 Array => np.arange( start_value, end_value, skip )

In [ ]:
order_array =
order_array

建立亂數 Array => np.random.random ( shape )

In [ ]:
random_array =
random_array

#### 取得 Numpy Array 的值

Array [ index ]

In [ ]:
# 取一維
one_dim

In [ ]:
# 取二維
two_dim

Array [ index1 : index2, index3 : index4 ]

In [ ]:
one_dim
#row = 0

In [ ]:
two_dim

Array [ condition ]

In [ ]:
one_dim
# output 數值>codition

In [ ]:
two_dim

#### 修改 Numpy Array 的值

Array [ index, index ] = value

In [ ]:
one_dim = 
one_dim

In [ ]:
two_dim = 
two_dim

#### 刪除 Numpy Array 的值

np.delete ( Array, [ index, index ], #axis=0/1 )

In [ ]:
np.delete

In [ ]:
np.delete(two_dim, [0], axis=0)#row

In [ ]:
np.delete(two_dim, [0], axis=1)# column

#### 新增 Numpy Array 的值

np.insert ( Array, index, value )

In [ ]:
# try one dim
np.insert

np.append ( Array, value )

In [ ]:
one_dim = 
one_dim

np.append ( Array1, Array2 )

In [ ]:
zero_array

In [ ]:
one_array

In [ ]:
np.append

### Numpy Array 的合併與切割

 - 垂直方向合併：np.vstack ( ( Array1, Array2 ) )
 - 水平方向合併：np.hstack ( ( Array1, Array2 ) )

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[9,8,7]])
array3 = np.vstack((array1, array2))
array3

In [ ]:
array4 = np.hstack((array1, array2))
array4

###### - 垂直方向合併：np.concatenate ( ( Array1, Array2 ), axis = 0 )
 - 水平方向合併：np.concatenate ( ( Array1, Array2 ), axis = 1 )

In [ ]:
array5 = np.concatenate((array1, array2), axis = 0)
array5

In [ ]:
array6 = np.concatenate((array1, array2), axis = 1)
array6

 - 垂直方向分割：np.vsplit ( Array, section )
 - 水平方向分割：np.hsplit ( Array, section )

In [ ]:
array7 = np.vsplit(array1, 2)
array7

In [ ]:
array8 = np.hsplit(array1, 3)
array8

### Numpy Array 的運算

Array1 + Array2

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array1+array2

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

Array1 - Array2

In [ ]:
array1-array2

Array1 * Array2

In [ ]:
array1 * array2

In [ ]:
list1 * 3

Array1 / Array2

In [ ]:
array1/array2

Array1 == Array2

In [ ]:
array1 == array2

np.array_equal ( Array1, Array2 )

In [ ]:
np.array_equal(array1, array2)

np.sqrt ( Array )

In [ ]:
np.sqrt(array1)
#平方根

np.log ( Array )

In [ ]:
np.log(array1)

Array.sum ( )

In [ ]:
array3 = np.array([[1,2,3],[4,5,6]])
array3.sum()

Array.sum ( axis = 0 )

In [ ]:
array3.sum(axis = 0)

Array.sum ( axis = 1 )

In [ ]:
array3.sum(axis = 1)

Array.max ( )

In [ ]:
array3.max()

Array.max ( axis = 0 )

In [ ]:
array3.max(axis = 0)

Array.max ( axis = 1 )

In [ ]:
array3.max(axis = 1)

Array.mean ( )

In [ ]:
array3.mean()
#算術平均數

Array.mean ( axis = 0 )

In [ ]:
array3.mean(axis = 0)

Array.mean ( axis = 1 )

In [ ]:
array3.mean(axis = 1)

另一種寫法：np.mean ( Array, axis = 0 )

In [ ]:
array3.mean()

### Numpy Array 的屬性

Array.ndim => Array 的 N 維

In [ ]:
array3

In [ ]:
array3.ndim

Array.shape => Array 的維度

In [ ]:
array3.shape

np.reshape ( Array, shape )

In [ ]:
np.reshape(array3, (3,2))
#(row,column)(0~2,0~1)>>3 rows * 2 columns

In [ ]:
np.reshape(array3, (3,3))

#### >>>為何上例會發生錯誤？<<<

#### >>>練習：array3 還可以轉換成何種維度，至少舉一例。<<<

In [ ]:
#your code


Array.size => Array 的元素個數

In [ ]:
array3.size

In [ ]:
len(array3)

np.resize ( Array, shape )

In [ ]:
np.resize(array3, (3,2))

In [ ]:
np.resize(array3, (3,3))

Array.dtype

In [ ]:
array3.dtype

Array.astype ( DataType )

In [ ]:
array3.astype(float)

### Numpy Array 資料讀寫 (I/O)

儲存 Numpy 資料格式檔案 => np.save ( file_name, Array )

In [ ]:
np.save('my_array', array1) # my_array.npy

讀取 Numpy 資料格式檔案 => np.load ( file_name )

In [ ]:
array_load = np.load('my_array.npy')
array_load

### Reference
 - https://numpy.org/
 - https://medium.com/python4u/hello-numpy-b5ebe67a1ada
 - http://cs231n.github.io/python-numpy-tutorial/
 - https://www.delftstack.com/zh-tw/tutorial/python-numpy/numpy-array-reshape-and-resize/

#### >>>練習<<<

請先 restart kernel，接著直接執行以下程式，程式結果將下載 score.npy 檔案

In [ ]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=18xJ4LuGtwq1JRsHJrY3lZYsy9vjTfI9-'
urlretrieve(url, "score.npy")

請用 numpy 讀取 score.npy 檔案，並將讀取結果指派給變數 score

In [ ]:
#your code


score 中依序紀錄了學生的姓名、國文成績、英文成績、數學成績，請問 score 中有多少個學生的資料 ?

In [ ]:
#your code


請刪除 score 中每筆資料的學生姓名  
Hint: `axis`

In [ ]:
#your code


請製作一個 Function 符合以下條件：
 - Function 名稱為 calculat_score_mean
 - 輸入參數為前題刪除完學生姓名的 score
 - 輸出為國文、英文、數學三個平均分數
 - 請使用製作好的 Function，print 出國文、英文、數學三個平均分數

In [ ]:
#your code


---

## Pandas
> Pandas 簡介<br>
> Series 的建立<br>
> Series 的操作<br>
> DataFrame 的建立<br>
> DataFrame 的操作<br>
> DataFrame feat. 統計資料<br>
> DataFrame feat. 資料處理

### Pandas 簡介
 - Numpy 是以 Array 形式呈現
 - Pandas 是以 Numpy 為基礎，提供三種資料結構：Series(一維)、DataFrame(二維)、Panel(三維)
 - Series 可看成可調整 index 的 Array，使用上須注意位置和 index 的差別
 - DataFrame 可看成可調整 index 和 column 的多個 Series

導入 Pandas

In [4]:
!pip install pandas
import pandas as pd

### Series 的建立

利用 List/Array 建立 Series

In [5]:
series_a = pd.Series([1,2,3,4,5])
series_a

0    1
1    2
2    3
3    4
4    5
dtype: int64

利用 Dictionary 建立 Series

In [ ]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

取得 index

In [ ]:
series_b.index

取得 values

In [ ]:
series_b.values

### Series 的操作
> Series 的取值<br>
> Series 的新增<br>
> Series 的刪除<br>
> Series 的修改

#### Series 的取值

利用 `index` 取值

In [ ]:
series_a[1]

In [ ]:
series_b['Mary']

一次取多值

In [ ]:
series_a[0:2]

In [ ]:
series_a[[0,2]]

利用 `.iloc[ ]` 取值 => 參數為位置

In [ ]:
series_a.iloc[0]

In [ ]:
series_a.iloc[0:2]

In [ ]:
series_a.iloc[[0,2]]

In [ ]:
series_b.iloc[0:2]

In [ ]:
series_b.iloc['Tom']

#### >>>請解釋上例錯誤的原因？<<<

利用 `.loc[ ]` 取值 => 參數為 index

In [ ]:
series_b.loc['Tom']

In [ ]:
series_b.loc['Tom':'Mary']

In [ ]:
series_b.loc[['Tom','Mary']]

In [ ]:
series_b.loc[0]

#### >>>請解釋上例錯誤的原因？<<<

利用 `條件式` 取值

In [ ]:
series_b[series_b < 170]

In [ ]:
# 多條件時需要 (1)將每個條件括號起來 (2)使用 & | 符號，不要用 and 跟 or
series_b[(series_b > 150) & (series_b < 170)]

In [ ]:
# 多條件時需要 (1)將每個條件括號起來 (2)使用 & | 符號，不要用 and 跟 or
series_b[(series_b > 150) and (series_b < 170)]

#### Series 的新增

使用 `append( )` 新增

In [ ]:
series_c = series_a.append(pd.Series([6,7,8]))
series_c

In [ ]:
series_c = series_a.append(pd.Series([6,7,8]), ignore_index=True)
series_c

In [ ]:
# another way!
series_c = series_a.append(pd.Series([6,7,8]))
series_c.reindex()

利用 `pd.concat( [ ] )` 新增

In [ ]:
series_d = pd.concat([series_a, series_b]) 
series_d

In [ ]:
series_d = pd.concat([series_a, series_b], ignore_index=True) 
series_d

利用取值方式新增

In [ ]:
series_c[9]=10
series_c

#### Series 的修改

使用 `index` 修改 

In [ ]:
series_b.loc['Mary'] = 190
series_b

使用 `位置` 修改

In [ ]:
series_b.iloc[0] = 190
series_b

請問如何將 series_b 180以下的數值都改成190?

In [ ]:
series_b.loc[series_b<=180] = 190
series_b

補充：用 `dict` 建立

In [ ]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

#### Series 的刪除

利用 `drop( )` 刪除 => 後面需使用 index

In [ ]:
series_c = series_b.drop(['Tom','Mary'])
series_c

In [ ]:
series_c = series_b.drop(0) # 使用位置會出錯
series_c

Series 跟 Array 最大的不同是 index 的處理，有時會因此在使用上比較便利，但往往也存在替代方案。可參考 [Pandas 官方文件](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html)

### DataFrame 的建立

利用 List/Array 建立 DataFrame

In [6]:
df_a = pd.DataFrame([[1,2,3],[4,5,6]])
df_a

0  1  2
0  1  2  3
1  4  5  6

建立 DataFrame 同時設定欄位

In [7]:
column_name = ['a','b','c']
df_a = pd.DataFrame([[1,2,3],[4,5,6]],columns=column_name)
df_a

a  b  c
0  1  2  3
1  4  5  6

利用 Dictionary 建立 DataFrame

In [8]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}

df_b = pd.DataFrame(dict_b)
df_b

Height  Weight
0     150      40
1     160      50
2     170      60
3     180      70
4     170      80
5     160      70
6     150      60
7     170      50
8     180      60
9     200      90

建立 DataFrame 同時設定 index

In [9]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}
index_list = ['Mary','Jane','Bob','Jack','Peter','Ben','Janet','Wind','Angle','John']

df_b = pd.DataFrame(dict_b, index=index_list)
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

取得欄位

In [10]:
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

In [12]:
df_b.columns

Index(['Height', 'Weight'], dtype='object')

取得 index

In [13]:
df_b.index

Index(['Mary', 'Jane', 'Bob', 'Jack', 'Peter', 'Ben', 'Janet', 'Wind', 'Angle',
       'John'],
      dtype='object')

取得 values

In [14]:
df_b.values

array([[150,  40],
       [160,  50],
       [170,  60],
       [180,  70],
       [170,  80],
       [160,  70],
       [150,  60],
       [170,  50],
       [180,  60],
       [200,  90]], dtype=int64)

取得資料筆數

In [15]:
len(df_b)

10

取得矩陣大小

In [16]:
df_b.shape # 10筆資料，2個欄位

(10, 2)

取得前五筆資料

In [17]:
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

In [18]:
# head() 預設是取得前五筆資料。
df_b.head()

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80

In [19]:
# head(n) 可以指定傳回筆數 n。
df_b.head(3)

Height  Weight
Mary     150      40
Jane     160      50
Bob      170      60

取得末五筆資料

In [21]:
df_b.tail()

Height  Weight
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

### DataFrame 的操作
> DataFrame 的取值<br>
> DataFrame 的新增<br>
> DataFrame 的修改<br>
> DataFrame 的刪除

#### DataFrame 的取值

利用欄位取值 => 會取得整欄的資料

In [22]:
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

In [25]:
df_b['Weight']

pandas.core.series.Series

In [26]:
df_b.Weight

Mary     40
Jane     50
Bob      60
Jack     70
Peter    80
Ben      70
Janet    60
Wind     50
Angle    60
John     90
Name: Weight, dtype: int64

利用欄位取值的型態是??

In [ ]:
type(df_b['Weight'])

利用`iloc[ ]`取值

In [27]:
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

In [28]:
df_b.iloc[3, 1]

70

In [31]:
df_b.iloc[:6, 0:2]

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70

請問該如何用`.iloc[ ]`同時只取出 Mary 和 Jack 的身高?

In [32]:
df_b.iloc[[0,3],0]

Mary    150
Jack    180
Name: Height, dtype: int64

利用`loc[ ]`取值

In [33]:
df_b.loc['Jack','Height']

180

In [34]:
df_b.loc['Jack':'Ben','Height':'Weight']

Height  Weight
Jack      180      70
Peter     170      80
Ben       160      70

In [35]:
df_b.loc[['Jack','Mary'],'Height']

Jack    180
Mary    150
Name: Height, dtype: int64

利用 `條件式` 取值

In [36]:
df_b[df_b['Weight']>70]

Height  Weight
Peter     170      80
John      200      90

In [37]:
df_b['Height'][df_b['Weight']>70]

Peter    170
John     200
Name: Height, dtype: int64

In [38]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b.loc[condition1 & condition2]

Height  Weight
John     200      90

如果想轉成 List 該怎麼做?

In [39]:
list_b = df_b['Height'].values.tolist()
print(list_b)
print(type(list_b))

[150, 160, 170, 180, 170, 160, 150, 170, 180, 200]
<class 'list'>


#### DataFrame 的新增

使用 `append( )` 新增

In [40]:
df_a

a  b  c
0  1  2  3
1  4  5  6

In [42]:
df_c = df_a.append(pd.DataFrame([[7,8,9]],columns=['a','b','c']), ignore_index=True)
df_c

C:\Users\user\AppData\Local\Temp\ipykernel_7092\1580519123.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_c = df_a.append(pd.DataFrame([[7,8,9]],columns=['a','b','c']), ignore_index=True)


a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

利用 `pd.concat( [ ] )` 新增

In [43]:
df_d = pd.concat([df_a,df_c],ignore_index=True)
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9

利用取值方式新增

In [44]:
df_d.loc[5] = [1,2,3]
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9
5  1  2  3

#### DataFrame 的修改

利用位置修改

In [45]:
df_b.iloc[0,0] = 170
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

利用 index 及 column 修改

In [46]:
df_b.loc['Angle','Weight'] = 70
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      200      90

利用條件式修改

In [47]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b[condition1 & condition2] = 100 # 整筆資料都會變成 100
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      100     100

In [48]:
condition1 = df_b['Weight']<70
condition2 = df_b['Height']<160
df_b['Height'][condition1 & condition2] = 180 # 只有身高會變成 180
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

#### DataFrame 的刪除

利用 `drop( )` 刪除

In [49]:
df_c = df_b.drop('Mary')
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [50]:
df_c = df_b.drop(['Mary','Ben'])
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [51]:
df_c = df_b.drop('Height',axis=1)
df_c

Weight
Mary       40
Jane       50
Bob        60
Jack       70
Peter      80
Ben        70
Janet      60
Wind       50
Angle      70
John      100

### DataFrame feat. 統計資料

總共出現了哪些資料 => unique( )

In [52]:
df_b['Height'].unique()

array([170, 160, 180, 100], dtype=int64)

每種資料出現的次數 => value_counts( )

In [53]:
df_b['Height'].value_counts()

170    4
180    3
160    2
100    1
Name: Height, dtype: int64

最大值與最小值 => max( )、min( )

In [54]:
df_b['Height'].max()

180

In [55]:
df_b['Height'].min()

100

總和 => sum( )

In [56]:
df_b['Height'].sum()

1640

累加值 => cumsum( )

In [57]:
df_b['Height'].cumsum()

Mary      170
Jane      330
Bob       500
Jack      680
Peter     850
Ben      1010
Janet    1190
Wind     1360
Angle    1540
John     1640
Name: Height, dtype: int64

平均值 => mean( axis )

In [58]:
df_b.mean() # 預設為垂直平均

Height    164.0
Weight     65.0
dtype: float64

In [59]:
df_b.mean(axis=1) # 水平平均

Mary     105.0
Jane     105.0
Bob      115.0
Jack     125.0
Peter    125.0
Ben      115.0
Janet    120.0
Wind     110.0
Angle    125.0
John     100.0
dtype: float64

標準差 => std( )

In [60]:
df_b.std() # 預設為垂直標準差

Height    23.664319
Weight    17.159384
dtype: float64

In [61]:
df_b.std(axis=1) # 水平標準差

Mary     91.923882
Jane     77.781746
Bob      77.781746
Jack     77.781746
Peter    63.639610
Ben      63.639610
Janet    84.852814
Wind     84.852814
Angle    77.781746
John      0.000000
dtype: float64

顯示常用的統計資料 => describe( )

In [62]:
df_b.describe()

Height      Weight
count   10.000000   10.000000
mean   164.000000   65.000000
std     23.664319   17.159384
min    100.000000   40.000000
25%    162.500000   52.500000
50%    170.000000   65.000000
75%    177.500000   70.000000
max    180.000000  100.000000

### DataFrame feat. 資料處理

#### 遺漏值處理

設定為遺漏值

In [63]:
import numpy as np
df_b.iloc[0,1] = np.nan
df_b

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

確認是否為遺漏值 => isnull( )

In [64]:
df_b.isnull()

Height  Weight
Mary    False    True
Jane    False   False
Bob     False   False
Jack    False   False
Peter   False   False
Ben     False   False
Janet   False   False
Wind    False   False
Angle   False   False
John    False   False

確認有多少個遺漏值

In [65]:
df_b.isnull().sum()

Height    0
Weight    1
dtype: int64

In [66]:
df_b.isnull().sum().sum()

1

刪除遺漏值 => dropna( )

In [67]:
df_b.dropna()

Height  Weight
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

填補遺漏值 => fillna( )

In [68]:
df_b.fillna(0)

Height  Weight
Mary      170     0.0
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

更多關於遺漏值的處理可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)

#### 處理重複資料

是否出現重複資料 => duplicated( )

In [69]:
df_b.duplicated() # 所有資料都一樣才會判定為重複資料

Mary     False
Jane     False
Bob      False
Jack     False
Peter    False
Ben      False
Janet    False
Wind     False
Angle     True
John     False
dtype: bool

刪除重複資料 => drop_duplicates( )

In [70]:
df_b.drop_duplicates()

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
John      100   100.0

指定欄位的資料重複時即刪除資料

In [71]:
df_b.drop_duplicates('Height')

Height  Weight
Mary     170     NaN
Jane     160    50.0
Jack     180    70.0
John     100   100.0

#### 資料排序

將 index/column 排序 => sort_index( )

In [ ]:
df_b.sort_index() # index 由小到大排序

In [ ]:
df_b.sort_index(axis=1, ascending=False) # columns 由大到小排序

將資料排序 => sort_values( )

In [ ]:
df_b.sort_values(by='Height')

In [ ]:
df_b.sort_values(by=['Height','Weight'])

#### 資料對應

利用 `map( )` 執行資料對應

In [ ]:
dig_to_cat = {100:'low', 160:'low', 170:'mid', 180:'high'}
df_b['cat'] = df_b['Height'].map(dig_to_cat)
df_b

#### 資料分箱

利用 `cut( )` 執行資料分箱

In [ ]:
Height = df_b['Height']
bins = [0,150,170,180]
Height_bins = pd.cut(Height, bins)
Height_bins.value_counts().sort_index()

In [ ]:
Height_bins

利用資料分箱標籤

In [ ]:
Height = df_b['Height']
bins = [0,150,170,180]
labels_list = ['low','mid','high']
df_b['label'] = pd.cut(Height, bins, labels=labels_list)
df_b

#### 資料轉換

利用 `apply( )` 作資料轉換

In [ ]:
# step1：define function
def change_to_ft(m):
    ft = m / 30.48
    return ft

# step2：put function into apply
df_b['ft'] = df_b['Height'].apply(change_to_ft)
df_b

如何計算BMI? 需要同時運用多個欄位該怎麼做?

In [ ]:
def get_BMI(row):
    height = row['Height']
    weight = row['Weight']
    BMI = weight / ((height*0.01)**2)
    return BMI

df_b['BMI'] = df_b.apply(get_BMI, axis=1)
df_b

更多關於 Pandas 的運用可以參考 [官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#selection)

---

# Input/Output (I/O)
> 使用 open()<br>
> 使用 Pandas

### 使用 open()

open( 資料路徑, 讀寫狀態, (編碼方式) )

 - 資料路徑可輸入相對路徑或絕對路徑
 - 讀寫狀態有 `r` (read) / `w` (write) / `a` (append)
 - 編碼方式通常在 windows 電腦須設定為 utf8
 - 每次使用完 open( ) 記得要 close( )

In [ ]:
# 請先執行以下程式下載資料
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1hfVebWsiQ16_EAZ7Q7jZzyJnBXM8TMN0'
urlretrieve(url, "students.csv")
url = 'https://drive.google.com/uc?export=download&id=1UujMIG2WxsH2kqaE_rgJ8BjpYYMsOb9f'
urlretrieve(url, "students.xlsx")

#### 讀取資料

In [ ]:
file = open('students.csv', 'r', encoding='utf8')
data = file.read()
file.close()

觀察 data 長什麼樣子

In [ ]:
data

In [ ]:
print(data)

如何整理讀到的 data

In [ ]:
lines = data.splitlines()
names = []
height = []
weight = []
for line in lines:
    items = line.split(',')
    names.append(items[0])
    height.append(items[1])
    weight.append(items[2])

In [ ]:
names

In [ ]:
height

In [ ]:
weight

#### 寫入資料

In [ ]:
file = open('names.txt', 'w', encoding='utf8') # 資料夾會出現 names.txt
data = file.write('\n'.join(names))
file.close()

#### 增加資料

In [ ]:
file = open('names.txt', 'a', encoding='utf8')
data = file.write(f'\nRachel')
file.close()

#### 實在覺得 close( ) 很煩，可以試試 with

In [ ]:
# with 會在程式執行完後自動 close
with open('students.csv', 'r', encoding='utf8') as file:
    names = []
    height = []
    weight = []
    for line in file.read().splitlines():
        items = line.split(',')
        names.append(items[0])
        height.append(items[1])
        weight.append(items[2])

### 使用 Pandas

#### 讀取資料

In [ ]:
df_csv = pd.read_csv('students.csv', header=None, encoding='utf-8')
df_csv

In [ ]:
df_xls = pd.read_excel('students.xlsx', sheet_name='工作表1', header=None)
df_xls

#### 寫入資料

In [ ]:
df_csv.to_csv('new_students.csv', encoding='utf-8')

In [ ]:
df_xls.to_excel('new_students.xlsx')

更多 Pandas 讀取資料格式可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

#### >>>練習：數值轉換，新增欄位，取值<<<

請先 restart kernel，接著直接執行以下程式，程式結果將下載 iris.csv 檔案

In [ ]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1DxOmm3dK2X0shq9h7XgyYI7FMi8OuUkv'
urlretrieve(url, "iris.csv")

請使用 open( ) 讀取 iris.csv，請 print 出 '共有 ? 筆資料, ? 個欄位'

In [ ]:
#your code


請使用 Pandas 讀取 iris.csv，將讀取到的 DataFrame 指派給變數 iris，並顯示前五筆資料

In [ ]:
#your code


請問資料中共有幾筆遺漏值?

In [ ]:
#your code


請將遺漏值刪除，並 print 出 '刪除遺漏值後資料筆數為 ? 筆'

In [ ]:
#your code


請將資料新增四個欄位，分別為欄位一到欄位四的 dummy variable (小於欄位平均數為 0，大於等於欄位平均數為 1)
> 範例如下：

||0|1|2|3|4|5|6|7|8|
|-|-|-|-|-|-|-|-|-|-|
|0|5.1|3.5|1.4|0.2|Iris-setosa|0|1|0|0|
|1|4.9|3.0|1.4|0.2|Iris-setosa|0|0|0|0|


In [ ]:
#your code


請將新增的四欄轉成 Numpy Array，並指派給變數 train_x

In [ ]:
#your code


請再將資料新增一個欄位，把第五欄的資料的 Iris-setosa -> 0, Iris-versicolor-> 1, Iris-virginica -> 2

In [ ]:
#your code


請將新增的一欄轉成 Numpy Array，並指派給變數 train_y

In [ ]:
#your code
