# 基礎程式設計 LAB 3

>[Numpy](#Numpy)<br>
>[Pandas](#Pandas)<br>
>[I/O: Input and Output](#Input/Output-(I/O))

Name: Hsiu-Yu Wang

Student ID:10316

# Numpy
> Numpy 簡介<br>
> Numpy Array 的基本操作<br>
> Numpy Array 的合併與切割<br>
> Numpy Array 的運算<br>
> Numpy Array 的屬性<br>
> Numpy Array 資料讀寫

### Numpy 簡介
 - 資料科學和機器學習常用的資料結構
 - 裝載相同類型資料的多維陣列
 - 較 List 高效且擁有多項功能，使用上須注意與 List 的差異
 - shape：資料維度, ex. (2,3) 代表 2x3 的矩陣
 - dtype：資料型態, 陣列中元素的型態
 - 使用前須先導入 numpy 函式庫

導入 Numpy 函式庫

In [2]:
import numpy as np

### Numpy Array 的基本操作
> 建立 Numpy Array<br>
> 取得 Numpy Array 的值<br>
> 修改 Numpy Array 的值<br>
> 新增 Numpy Array 的值<br>
> 刪除 Numpy Array 的值

#### 建立 Numpy Array

使用 List 建立 Array => np.array ( List )

In [3]:
# 一維 Array
one_dim = 
one_dim
# array([1, 2, 3])

array([1, 2, 3])

In [35]:
# 二維 Array
two_dim = 
two_dim
# array([[1, 2, 3],
#        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
# 三維 Array
three_dim = 
three_dim
# array([[[1, 2, 3],
#         [4, 5, 6]],
# 
#        [[7, 8, 9],
#         [9, 8, 7]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [9, 8, 7]]])

建立全為 0 的 Array => np.zeros ( shape )

In [37]:
zero_array = 
zero_array
# array([[0., 0., 0.],
#        [0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

建立全為 1 的 Array => np.ones ( shape )

In [38]:
# 試試看建立成三維
one_array = 
one_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

建立指定數值的 Array => np.full ( shape, number )

In [39]:
# try int
eight_array = 
eight_array

array([[8, 8, 8],
       [8, 8, 8]])

In [40]:
# try float
one_array = 
one_array

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

建立有序數列的 Array => np.arange( start_value, end_value, skip )

In [41]:
order_array =
order_array

array([0, 2, 4, 6, 8])

建立亂數 Array => np.random.random ( shape )

In [42]:
random_array =
random_array

array([[0.17118845, 0.7096092 , 0.25700825],
       [0.11355133, 0.39212478, 0.53260579]])

#### 取得 Numpy Array 的值

Array [ index ]

In [43]:
# 取一維
one_dim

3

In [44]:
# 取二維
two_dim

6

Array [ index1 : index2, index3 : index4 ]

In [45]:
one_dim
#row = 0

array([1, 2])

In [46]:
two_dim

array([[1, 2],
       [4, 5]])

Array [ condition ]

In [48]:
one_dim
# output 數值>codition

array([2, 3])

In [50]:
two_dim

array([4, 5, 6])

#### 修改 Numpy Array 的值

Array [ index, index ] = value

In [51]:
one_dim = 
one_dim

array([9, 2, 3])

In [52]:
two_dim = 
two_dim

array([[1, 2, 3],
       [4, 5, 9]])

#### 刪除 Numpy Array 的值

np.delete ( Array, [ index, index ], #axis=0/1 )

In [91]:
np.delete

array([9])

In [93]:
np.delete(two_dim, [0], axis=0)#row

array([[4, 5, 9]])

In [95]:
np.delete(two_dim, [0], axis=1)# column

array([[2, 3],
       [5, 9]])

#### 新增 Numpy Array 的值

np.insert ( Array, index, value )

In [96]:
np.insert(one_dim, 0, 5)

array([5, 9, 2, 3])

np.append ( Array, value )

In [97]:
one_dim = np.append(one_dim, 7)
one_dim

array([9, 2, 3, 7])

np.append ( Array1, Array2 )

In [98]:
np.append(zero_array, one_array)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Numpy Array 的合併與切割

 - 垂直方向合併：np.vstack ( ( Array1, Array2 ) )
 - 水平方向合併：np.hstack ( ( Array1, Array2 ) )

In [99]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[9,8,7]])
array3 = np.vstack((array1, array2))
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [100]:
array4 = np.hstack((array1, array2))
array4

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

###### - 垂直方向合併：np.concatenate ( ( Array1, Array2 ), axis = 0 )
 - 水平方向合併：np.concatenate ( ( Array1, Array2 ), axis = 1 )

In [101]:
array5 = np.concatenate((array1, array2), axis = 0)
array5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [102]:
array6 = np.concatenate((array1, array2), axis = 1)
array6

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 9, 8, 7]])

 - 垂直方向分割：np.vsplit ( Array, section )
 - 水平方向分割：np.hsplit ( Array, section )

In [103]:
array7 = np.vsplit(array1, 2)
array7

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [104]:
array8 = np.hsplit(array1, 3)
array8

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

### Numpy Array 的運算

Array1 + Array2

In [105]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array1+array2

array([5, 7, 9])

In [106]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

Array1 - Array2

In [107]:
array1-array2

array([-3, -3, -3])

Array1 * Array2

In [108]:
array1 * array2

array([ 4, 10, 18])

In [109]:
list1 * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Array1 / Array2

In [110]:
array1/array2

array([0.25, 0.4 , 0.5 ])

Array1 == Array2

In [111]:
array1 == array2

array([False, False, False])

np.array_equal ( Array1, Array2 )

In [112]:
np.array_equal(array1, array2)

False

np.sqrt ( Array )

In [113]:
np.sqrt(array1)
#平方根

array([1.        , 1.41421356, 1.73205081])

np.log ( Array )

In [114]:
np.log(array1)

array([0.        , 0.69314718, 1.09861229])

Array.sum ( )

In [115]:
array3 = np.array([[1,2,3],[4,5,6]])
array3.sum()

21

Array.sum ( axis = 0 )

In [116]:
array3.sum(axis = 0)

array([5, 7, 9])

Array.sum ( axis = 1 )

In [117]:
array3.sum(axis = 1)

array([ 6, 15])

Array.max ( )

In [118]:
array3.max()

6

Array.max ( axis = 0 )

In [119]:
array3.max(axis = 0)

array([4, 5, 6])

Array.max ( axis = 1 )

In [120]:
array3.max(axis = 1)

array([3, 6])

Array.mean ( )

In [121]:
array3.mean()
#算術平均數

3.5

Array.mean ( axis = 0 )

In [122]:
array3.mean(axis = 0)

array([2.5, 3.5, 4.5])

Array.mean ( axis = 1 )

In [123]:
array3.mean(axis = 1)

array([2., 5.])

另一種寫法：np.mean ( Array, axis = 0 )

In [124]:
array3.mean()

3.5

### Numpy Array 的屬性

Array.ndim => Array 的 N 維

In [125]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
array3.ndim

2

Array.shape => Array 的維度

In [127]:
array3.shape

(2, 3)

np.reshape ( Array, shape )

In [128]:
np.reshape(array3, (3,2))
#(row,column)(0~2,0~1)>>3 rows * 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
np.reshape(array3, (3,3))

ValueError: cannot reshape array of size 6 into shape (3,3)

#### >>>回家練習：請解釋為何上例會發生錯誤？<<<

#### your answer:
已經reshape建立3,2共6個值的array，若reshape 3,3需9個值

#### >>>回家練習：array3 還可以轉換成何種維度，至少舉一例。<<<

In [143]:
#your code
array3.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Array.size => Array 的元素個數

In [144]:
array3.size

6

In [145]:
len(array3)

2

Array.resize ( shape )

In [146]:
np.resize(array3, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
np.resize(array3, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

Array.dtype

In [148]:
array3.dtype

dtype('int32')

Array.astype ( DataType )

In [149]:
array3.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.]])

### Numpy Array 資料讀寫 (I/O)

儲存 Numpy 資料格式檔案 => np.save ( file_name, Array )

In [150]:
np.save('my_array', array1) # my_array.npy

讀取 Numpy 資料格式檔案 => np.load ( file_name )

In [151]:
array_load = np.load('my_array.npy')
array_load

array([1, 2, 3])

### Reference
 - https://numpy.org/
 - https://medium.com/python4u/hello-numpy-b5ebe67a1ada
 - http://cs231n.github.io/python-numpy-tutorial/
 - https://www.delftstack.com/zh-tw/tutorial/python-numpy/numpy-array-reshape-and-resize/

#### >>>回家練習<<<

請先 restart kernel，接著直接執行以下程式，程式結果將下載 score.npy 檔案

In [2]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1dHKNkvAsWC96Qi985YIotRxXhIpSQP3-'
urlretrieve(url, "score.npy")

('score.npy', <http.client.HTTPMessage at 0x2106c65b6a0>)

請用 numpy 讀取 score.npy 檔案，並將讀取結果指派給變數 score

In [3]:
#your code
import numpy as np

score = np.load('score.npy')
score

array([['Aaron', '37', '70', '15'],
       ['Abel', '27', '64', '41'],
       ['Abraham', '14', '53', '77'],
       ...,
       ['Virginia', '39', '85', '6'],
       ['Vita', '29', '65', '20'],
       ['Vivian', '80', '24', '52']], dtype='<U11')

score 中依序紀錄了學生的姓名、國文成績、英文成績、數學成績，請問 score 中有多少個學生的資料 ?

In [51]:
#your code
score.shape

(568, 4)

請刪除 score 中每筆資料的學生姓名

In [5]:
#your code
np.delete(score,[0],axis=1)

array([['37', '70', '15'],
       ['27', '64', '41'],
       ['14', '53', '77'],
       ...,
       ['39', '85', '6'],
       ['29', '65', '20'],
       ['80', '24', '52']], dtype='<U11')

請製作一個 Function 符合以下條件：
 - Function 名稱為 calculat_score_mean
 - 輸入參數為前題刪除完學生姓名的 score
 - 輸出為國文、英文、數學三個平均分數
 - 請使用製作好的 Function，print 出國文、英文、數學三個平均分數

In [43]:
#your code
subject = ['國文', '英文', '數學']

def calculat_score_mean(pscore):
    pscore = np.delete(pscore,[0],axis=1)
    pscore = pscore.astype(np.float)
    pscore = pscore.mean(axis=0)
    return pscore
    
score = np.load('score.npy')
for i in range(3):
    print(f'{subject[i]}：平均{calculat_score_mean(score)[i]}分')

國文：平均50.390845070422536分
英文：平均50.67781690140845分
數學：平均50.32746478873239分


<ipython-input-43-e33d13f1e34a>:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pscore = pscore.astype(np.float)


---

## Pandas
> Pandas 簡介<br>
> Series 的建立<br>
> Series 的操作<br>
> DataFrame 的建立<br>
> DataFrame 的操作<br>
> DataFrame feat. 統計資料<br>
> DataFrame feat. 資料處理

### Pandas 簡介
 - Numpy 是以 Array 形式呈現
 - Pandas 是以 Numpy 為基礎，提供三種資料結構：Series(一維)、DataFrame(二維)、Panel(三維)
 - Series 可看成可調整 index 的 Array，使用上須注意位置和 index 的差別
 - DataFrame 可看成可調整 index 和 column 的多個 Series

導入 Pandas

In [2]:
import pandas as pd

### Series 的建立

利用 List/Array 建立 Series

In [3]:
series_a = pd.Series([1,2,3,4,5])
series_a

0    1
1    2
2    3
3    4
4    5
dtype: int64

利用 Dictionary 建立 Series

In [4]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

Tom      150
David    180
Mary     170
Jane     160
dtype: int64

取得 index

In [5]:
series_b.index

Index(['Tom', 'David', 'Mary', 'Jane'], dtype='object')

取得 values

In [6]:
series_b.values

array([150, 180, 170, 160], dtype=int64)

### Series 的操作
> Series 的取值<br>
> Series 的新增<br>
> Series 的刪除<br>
> Series 的修改

#### Series 的取值

利用 `index` 取值

In [7]:
series_a[1]

2

In [8]:
series_b['Mary']

170

一次取多值

In [9]:
series_a[0:2]

0    1
1    2
dtype: int64

In [10]:
series_a[[0,2]]

0    1
2    3
dtype: int64

利用 `.iloc[ ]` 取值 => 參數為位置

In [11]:
series_a.iloc[0]

1

In [12]:
series_a.iloc[0:2]

0    1
1    2
dtype: int64

In [13]:
series_a.iloc[[0,2]]

0    1
2    3
dtype: int64

In [14]:
series_b.iloc[0:2]

Tom      150
David    180
dtype: int64

In [15]:
series_b.iloc['Tom'] # 輸入非位置會出錯

TypeError: Cannot index by location index with a non-integer key

#### >>>回家作業：請解釋上例錯誤的原因？<<<

利用 `.loc[ ]` 取值 => 參數為 index

In [16]:
series_b.loc['Tom']

150

In [17]:
series_b.loc['Tom':'Mary']

Tom      150
David    180
Mary     170
dtype: int64

In [18]:
series_b.loc[['Tom','Mary']]

Tom     150
Mary    170
dtype: int64

In [19]:
series_b.loc[0] # 輸入非 index 會出錯

KeyError: 0

#### >>>回家作業：請解釋上例錯誤的原因？<<<

利用 `條件式` 取值

In [20]:
series_b[series_b<170]

Tom     150
Jane    160
dtype: int64

In [21]:
# 多條件時需要 (1)將每個條件括號起來 (2)使用 & | 符號，不要用 and 跟 or
series_b[(series_b>150) & (series_b<170)]

Jane    160
dtype: int64

In [22]:
# 多條件時需要 (1)將每個條件括號起來 (2)使用 & | 符號，不要用 and 跟 or
series_b[(series_b>150) and (series_b<170)]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

#### Series 的新增

使用 `append( )` 新增

In [23]:
series_c = series_a.append(pd.Series([6,7,8]))
series_c

0    1
1    2
2    3
3    4
4    5
0    6
1    7
2    8
dtype: int64

In [24]:
series_c = series_a.append(pd.Series([6,7,8]), ignore_index=True)
series_c

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [25]:
# or you can use reindex()
series_c = series_a.append(pd.Series([6,7,8]))
series_c.reindex()

0    1
1    2
2    3
3    4
4    5
0    6
1    7
2    8
dtype: int64

利用 `pd.concat( [ ] )` 新增

In [26]:
series_d = pd.concat([series_a, series_b]) 
series_d

0          1
1          2
2          3
3          4
4          5
Tom      150
David    180
Mary     170
Jane     160
dtype: int64

In [27]:
series_d = pd.concat([series_a, series_b], ignore_index=True) 
series_d

0      1
1      2
2      3
3      4
4      5
5    150
6    180
7    170
8    160
dtype: int64

利用取值方式新增

In [28]:
series_c[9]=10
series_c

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
9    10
dtype: int64

#### Series 的修改

使用 `index` 修改 

In [29]:
series_b.loc['Mary'] = 190
series_b

Tom      150
David    180
Mary     190
Jane     160
dtype: int64

使用 `位置` 修改

In [30]:
series_b.iloc[0] = 190
series_b

Tom      190
David    180
Mary     190
Jane     160
dtype: int64

請問如何將 series_b 180以下的數值都改成190?

In [31]:
series_b.loc[series_b<=180] = 190
series_b

Tom      190
David    190
Mary     190
Jane     190
dtype: int64

In [32]:
dict_b = {'Tom':150, 'David':180, 'Mary':170, 'Jane':160}

series_b = pd.Series(dict_b)
series_b

Tom      150
David    180
Mary     170
Jane     160
dtype: int64

#### Series 的刪除

利用 `drop( )` 刪除 => 後面需使用 index

In [33]:
series_c = series_b.drop(['Tom','Mary'])
series_c

David    180
Jane     160
dtype: int64

In [34]:
series_c = series_b.drop(0) # 使用位置會出錯
series_c

KeyError: '[0] not found in axis'

Series 跟 Array 最大的不同是 index 的處理，有時會因此在使用上比較便利，但往往也存在替代方案。因此課堂上不會在此多作著墨，同學如有興趣可參考 [Pandas 官方文件](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.html)

### DataFrame 的建立

利用 List/Array 建立 DataFrame

In [35]:
df_a = pd.DataFrame([[1,2,3],[4,5,6]])
df_a

0  1  2
0  1  2  3
1  4  5  6

建立 DataFrame 同時設定欄位

In [36]:
column_name = ['a','b','c']
df_a = pd.DataFrame([[1,2,3],[4,5,6]],columns=column_name)
df_a

a  b  c
0  1  2  3
1  4  5  6

利用 Dictionary 建立 DataFrame

In [37]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}

df_b = pd.DataFrame(dict_b)
df_b

Height  Weight
0     150      40
1     160      50
2     170      60
3     180      70
4     170      80
5     160      70
6     150      60
7     170      50
8     180      60
9     200      90

建立 DataFrame 同時設定 index

In [38]:
dict_b = {'Height':[150,160,170,180,170,160,150,170,180,200],
          'Weight':[40,50,60,70,80,70,60,50,60,90]}
index_list = ['Mary','Jane','Bob','Jack','Peter','Ben','Janet','Wind','Angle','John']

df_b = pd.DataFrame(dict_b, index=index_list)
df_b

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

取得欄位

In [39]:
df_b.columns

Index(['Height', 'Weight'], dtype='object')

取得 index

In [40]:
df_b.index

Index(['Mary', 'Jane', 'Bob', 'Jack', 'Peter', 'Ben', 'Janet', 'Wind', 'Angle',
       'John'],
      dtype='object')

取得 values

In [10]:
df_b.values

NameError: name 'df_b' is not defined

取得資料筆數

In [42]:
len(df_b)

10

取得矩陣大小

In [43]:
df_b.shape # 10筆資料，2個欄位

(10, 2)

取得前五筆資料

In [44]:
# head() 預設是取得前五筆資料。
df_b.head()

Height  Weight
Mary      150      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80

In [45]:
# head(n) 可以指定傳回筆數 n。
df_b.head(3)

Height  Weight
Mary     150      40
Jane     160      50
Bob      170      60

取得末五筆資料

In [46]:
df_b.tail()

Height  Weight
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

### DataFrame 的操作
> DataFrame 的取值<br>
> DataFrame 的新增<br>
> DataFrame 的修改<br>
> DataFrame 的刪除

#### DataFrame 的取值

利用欄位取值 => 會取得整欄的資料

In [47]:
df_b['Weight']

Mary     40
Jane     50
Bob      60
Jack     70
Peter    80
Ben      70
Janet    60
Wind     50
Angle    60
John     90
Name: Weight, dtype: int64

In [48]:
df_b.Weight

Mary     40
Jane     50
Bob      60
Jack     70
Peter    80
Ben      70
Janet    60
Wind     50
Angle    60
John     90
Name: Weight, dtype: int64

利用欄位取值的型態是??

In [49]:
type(df_b['Weight'])

pandas.core.series.Series

利用`iloc[ ]`取值

In [50]:
df_b.iloc[3,1]

70

In [51]:
df_b.iloc[1:3,0:2]

Height  Weight
Jane     160      50
Bob      170      60

請問該如何用`.iloc[ ]`同時只取出 Mary 和 Jack 的身高?

In [52]:
df_b.iloc[[0,3],0]

Mary    150
Jack    180
Name: Height, dtype: int64

利用`loc[ ]`取值

In [53]:
df_b.loc['Jack','Height']

180

In [54]:
df_b.loc['Jack':'Ben','Height':'Weight']

Height  Weight
Jack      180      70
Peter     170      80
Ben       160      70

In [55]:
df_b.loc[['Jack','Mary'],'Height']

Jack    180
Mary    150
Name: Height, dtype: int64

利用 `條件式` 取值

In [56]:
df_b[df_b['Weight']>70]

Height  Weight
Peter     170      80
John      200      90

In [57]:
df_b['Height'][df_b['Weight']>70]

Peter    170
John     200
Name: Height, dtype: int64

In [58]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b.loc[condition1 & condition2]

Height  Weight
John     200      90

如果想轉成 List 該怎麼做?

In [59]:
list_b = df_b['Height'].values.tolist()
print(list_b)
print(type(list_b))

[150, 160, 170, 180, 170, 160, 150, 170, 180, 200]
<class 'list'>


#### DataFrame 的新增

使用 `append( )` 新增

In [60]:
df_a

a  b  c
0  1  2  3
1  4  5  6

In [61]:
df_c = df_a.append(pd.DataFrame([[7,8,9]],columns=['a','b','c']),ignore_index=True)
df_c

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

利用 `pd.concat( [ ] )` 新增

In [62]:
df_d = pd.concat([df_a,df_c],ignore_index=True)
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9

利用取值方式新增

In [63]:
df_d.loc[5] = [1,2,3]
df_d

a  b  c
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  7  8  9
5  1  2  3

#### DataFrame 的修改

利用位置修改

In [64]:
df_b.iloc[0,0] = 170
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      60
John      200      90

利用 index 及 column 修改

In [65]:
df_b.loc['Angle','Weight'] = 70
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      200      90

利用條件式修改

In [66]:
condition1 = df_b['Weight']>70
condition2 = df_b['Height']>170
df_b[condition1 & condition2] = 100 # 整筆資料都會變成 100
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     150      60
Wind      170      50
Angle     180      70
John      100     100

In [67]:
condition1 = df_b['Weight']<70
condition2 = df_b['Height']<160
df_b['Height'][condition1 & condition2] = 180 # 只有身高會變成 180
df_b

Height  Weight
Mary      170      40
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

#### DataFrame 的刪除

利用 `drop( )` 刪除

In [68]:
df_c = df_b.drop('Mary')
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Ben       160      70
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [69]:
df_c = df_b.drop(['Mary','Ben'])
df_c

Height  Weight
Jane      160      50
Bob       170      60
Jack      180      70
Peter     170      80
Janet     180      60
Wind      170      50
Angle     180      70
John      100     100

In [70]:
df_c = df_b.drop('Height',axis=1)
df_c

Weight
Mary       40
Jane       50
Bob        60
Jack       70
Peter      80
Ben        70
Janet      60
Wind       50
Angle      70
John      100

### DataFrame feat. 統計資料

總共出現了哪些資料 => unique( )

In [71]:
df_b['Height'].unique()

array([170, 160, 180, 100], dtype=int64)

每種資料出現的次數 => value_counts( )

In [72]:
df_b['Height'].value_counts()

170    4
180    3
160    2
100    1
Name: Height, dtype: int64

最大值與最小值 => max( )、min( )

In [73]:
df_b['Height'].max()

180

In [74]:
df_b['Height'].min()

100

總和 => sum( )

In [75]:
df_b['Height'].sum()

1640

累加值 => cumsum( )

In [76]:
df_b['Height'].cumsum()

Mary      170
Jane      330
Bob       500
Jack      680
Peter     850
Ben      1010
Janet    1190
Wind     1360
Angle    1540
John     1640
Name: Height, dtype: int64

平均值 => mean( axis )

In [77]:
df_b.mean() # 預設為垂直平均

Height    164.0
Weight     65.0
dtype: float64

In [78]:
df_b.mean(axis=1) # 水平平均

Mary     105.0
Jane     105.0
Bob      115.0
Jack     125.0
Peter    125.0
Ben      115.0
Janet    120.0
Wind     110.0
Angle    125.0
John     100.0
dtype: float64

標準差 => std( )

In [79]:
df_b.std() # 預設為垂直標準差

Height    23.664319
Weight    17.159384
dtype: float64

In [80]:
df_b.std(axis=1) # 水平標準差

Mary     91.923882
Jane     77.781746
Bob      77.781746
Jack     77.781746
Peter    63.639610
Ben      63.639610
Janet    84.852814
Wind     84.852814
Angle    77.781746
John      0.000000
dtype: float64

顯示常用的統計資料 => describe( )

In [81]:
df_b.describe()

Height      Weight
count   10.000000   10.000000
mean   164.000000   65.000000
std     23.664319   17.159384
min    100.000000   40.000000
25%    162.500000   52.500000
50%    170.000000   65.000000
75%    177.500000   70.000000
max    180.000000  100.000000

### DataFrame feat. 資料處理

#### 遺漏值處理

設定為遺漏值

In [82]:
import numpy as np
df_b.iloc[0,1] = np.nan
df_b

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

確認是否為遺漏值 => isnull( )

In [83]:
df_b.isnull()

Height  Weight
Mary    False    True
Jane    False   False
Bob     False   False
Jack    False   False
Peter   False   False
Ben     False   False
Janet   False   False
Wind    False   False
Angle   False   False
John    False   False

確認有多少個遺漏值

In [84]:
df_b.isnull().sum()

Height    0
Weight    1
dtype: int64

In [85]:
df_b.isnull().sum().sum()

1

刪除遺漏值 => dropna( )

In [86]:
df_b.dropna()

Height  Weight
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

填補遺漏值 => fillna( )

In [87]:
df_b.fillna(0)

Height  Weight
Mary      170     0.0
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
Angle     180    70.0
John      100   100.0

更多關於遺漏值的處理可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html)

#### 處理重複資料

是否出現重複資料 => duplicated( )

In [88]:
df_b.duplicated() # 所有資料都一樣才會判定為重複資料

Mary     False
Jane     False
Bob      False
Jack     False
Peter    False
Ben      False
Janet    False
Wind     False
Angle     True
John     False
dtype: bool

刪除重複資料 => drop_duplicates( )

In [89]:
df_b.drop_duplicates()

Height  Weight
Mary      170     NaN
Jane      160    50.0
Bob       170    60.0
Jack      180    70.0
Peter     170    80.0
Ben       160    70.0
Janet     180    60.0
Wind      170    50.0
John      100   100.0

指定欄位的資料重複時即刪除資料

In [90]:
df_b.drop_duplicates('Height')

Height  Weight
Mary     170     NaN
Jane     160    50.0
Jack     180    70.0
John     100   100.0

#### 資料排序

將 index/column 排序 => sort_index( )

In [91]:
df_b.sort_index() # index 由小到大排序

Height  Weight
Angle     180    70.0
Ben       160    70.0
Bob       170    60.0
Jack      180    70.0
Jane      160    50.0
Janet     180    60.0
John      100   100.0
Mary      170     NaN
Peter     170    80.0
Wind      170    50.0

In [94]:
df_b.sort_index(axis=1, ascending=False) # columns 由大到小排序

Weight  Height
Mary      NaN     170
Jane     50.0     160
Bob      60.0     170
Jack     70.0     180
Peter    80.0     170
Ben      70.0     160
Janet    60.0     180
Wind     50.0     170
Angle    70.0     180
John    100.0     100

將資料排序 => sort_values( )

In [95]:
df_b.sort_values(by='Height')

Height  Weight
John      100   100.0
Jane      160    50.0
Ben       160    70.0
Mary      170     NaN
Bob       170    60.0
Peter     170    80.0
Wind      170    50.0
Jack      180    70.0
Janet     180    60.0
Angle     180    70.0

In [96]:
df_b.sort_values(by=['Height','Weight'])

Height  Weight
John      100   100.0
Jane      160    50.0
Ben       160    70.0
Wind      170    50.0
Bob       170    60.0
Peter     170    80.0
Mary      170     NaN
Janet     180    60.0
Jack      180    70.0
Angle     180    70.0

#### 資料對應

利用 `map( )` 執行資料對應

In [98]:
dig_to_cat = {100:'low', 160:'low', 170:'mid', 180:'high'}
df_b['cat'] = df_b['Height'].map(dig_to_cat)
df_b

Height  Weight   cat
Mary      170     NaN   mid
Jane      160    50.0   low
Bob       170    60.0   mid
Jack      180    70.0  high
Peter     170    80.0   mid
Ben       160    70.0   low
Janet     180    60.0  high
Wind      170    50.0   mid
Angle     180    70.0  high
John      100   100.0   low

#### 資料分箱

利用 `cut( )` 執行資料分箱

In [99]:
Height = df_b['Height']
bins = [0,150,170,180]
Height_bins = pd.cut(Height, bins)
Height_bins.value_counts().sort_index()

(0, 150]      1
(150, 170]    6
(170, 180]    3
Name: Height, dtype: int64

In [100]:
Height_bins

Mary     (150, 170]
Jane     (150, 170]
Bob      (150, 170]
Jack     (170, 180]
Peter    (150, 170]
Ben      (150, 170]
Janet    (170, 180]
Wind     (150, 170]
Angle    (170, 180]
John       (0, 150]
Name: Height, dtype: category
Categories (3, interval[int64]): [(0, 150] < (150, 170] < (170, 180]]

利用資料分箱標籤

In [101]:
Height = df_b['Height']
bins = [0,150,170,180]
labels_list = ['low','mid','high']
df_b['label'] = pd.cut(Height, bins, labels=labels_list)
df_b

Height  Weight   cat label
Mary      170     NaN   mid   mid
Jane      160    50.0   low   mid
Bob       170    60.0   mid   mid
Jack      180    70.0  high  high
Peter     170    80.0   mid   mid
Ben       160    70.0   low   mid
Janet     180    60.0  high  high
Wind      170    50.0   mid   mid
Angle     180    70.0  high  high
John      100   100.0   low   low

#### 資料轉換

利用 `apply( )` 作資料轉換

In [106]:
# step1：define function
def change_to_ft(m):
    ft = m / 30.48
    return ft

# step2：put function into apply
df_b['ft'] = df_b['Height'].apply(change_to_ft)
df_b

Height  Weight   cat label        ft         BMI
Mary      170     NaN   mid   mid  5.577428         NaN
Jane      160    50.0   low   mid  5.249344   19.531250
Bob       170    60.0   mid   mid  5.577428   20.761246
Jack      180    70.0  high  high  5.905512   21.604938
Peter     170    80.0   mid   mid  5.577428   27.681661
Ben       160    70.0   low   mid  5.249344   27.343750
Janet     180    60.0  high  high  5.905512   18.518519
Wind      170    50.0   mid   mid  5.577428   17.301038
Angle     180    70.0  high  high  5.905512   21.604938
John      100   100.0   low   low  3.280840  100.000000

如何計算BMI? 需要同時運用多個欄位該怎麼做?

In [104]:
def get_BMI(row):
    height = row['Height']
    weight = row['Weight']
    BMI = weight / ((height*0.01)**2)
    return BMI

df_b['BMI'] = df_b.apply(get_BMI, axis=1)
df_b

Height  Weight   cat label        ft         BMI
Mary      170     NaN   mid   mid  5.577428         NaN
Jane      160    50.0   low   mid  5.249344   19.531250
Bob       170    60.0   mid   mid  5.577428   20.761246
Jack      180    70.0  high  high  5.905512   21.604938
Peter     170    80.0   mid   mid  5.577428   27.681661
Ben       160    70.0   low   mid  5.249344   27.343750
Janet     180    60.0  high  high  5.905512   18.518519
Wind      170    50.0   mid   mid  5.577428   17.301038
Angle     180    70.0  high  high  5.905512   21.604938
John      100   100.0   low   low  3.280840  100.000000

更多關於 Pandas 的運用可以參考 [官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#selection)

---

# Input/Output (I/O)
> 使用 open()<br>
> 使用 Pandas

### 使用 open()

open( 資料路徑, 讀寫狀態, (編碼方式) )

 - 資料路徑可輸入相對路徑或絕對路徑
 - 讀寫狀態有 `r` (read) / `w` (write) / `a` (append)
 - 編碼方式通常在 windows 電腦須設定為 utf8
 - 每次使用完 open( ) 記得要 close( )

In [107]:
# 請先執行以下程式下載資料
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1hfVebWsiQ16_EAZ7Q7jZzyJnBXM8TMN0'
urlretrieve(url, "students.csv")
url = 'https://drive.google.com/uc?export=download&id=1UujMIG2WxsH2kqaE_rgJ8BjpYYMsOb9f'
urlretrieve(url, "students.xlsx")

('students.xlsx', <http.client.HTTPMessage at 0x1b62122f790>)

#### 讀取資料

In [111]:
file = open('students.csv', 'r', encoding='utf8')
data = file.read()
file.close()

觀察 data 長什麼樣子

In [112]:
data

'Jane,160,50\nBob,170,60\nJack,170,80\nPeter,170,80\nBen,160,70\nJanet,150,60\nWind,170,50\nAngle,180,90\n'

In [113]:
print(data)

Jane,160,50
Bob,170,60
Jack,170,80
Peter,170,80
Ben,160,70
Janet,150,60
Wind,170,50
Angle,180,90



如何整理讀到的 data

In [114]:
lines = data.splitlines()
names = []
height = []
weight = []
for line in lines:
    items = line.split(',')
    names.append(items[0])
    height.append(items[1])
    weight.append(items[2])

In [115]:
names

['Jane', 'Bob', 'Jack', 'Peter', 'Ben', 'Janet', 'Wind', 'Angle']

In [116]:
height

['160', '170', '170', '170', '160', '150', '170', '180']

In [117]:
weight

['50', '60', '80', '80', '70', '60', '50', '90']

#### 寫入資料

In [118]:
file = open('names.txt', 'w', encoding='utf8') # 資料夾會出現 names.txt
data = file.write('\n'.join(names))
file.close()

#### 增加資料

In [119]:
file = open('names.txt', 'a', encoding='utf8')
data = file.write(f'\nRachel')
file.close()

#### 實在覺得 close( ) 很煩，可以試試 with

In [120]:
# with 會在程式執行完後自動 close
with open('students.csv', 'r', encoding='utf8') as file:
    names = []
    height = []
    weight = []
    for line in file.read().splitlines():
        items = line.split(',')
        names.append(items[0])
        height.append(items[1])
        weight.append(items[2])

### 使用 Pandas

#### 讀取資料

In [121]:
df_csv = pd.read_csv('students.csv', header=None, encoding='utf-8')
df_csv

0    1   2
0   Jane  160  50
1    Bob  170  60
2   Jack  170  80
3  Peter  170  80
4    Ben  160  70
5  Janet  150  60
6   Wind  170  50
7  Angle  180  90

In [122]:
df_xls = pd.read_excel('students.xlsx', sheet_name='工作表1', header=None)
df_xls

0    1   2
0   Jane  160  50
1    Bob  170  60
2   Jack  170  80
3  Peter  170  80
4    Ben  160  70
5  Janet  150  60
6   Wind  170  50
7  Angle  180  90

#### 寫入資料

In [123]:
df_csv.to_csv('new_students.csv', encoding='utf-8')

In [124]:
df_xls.to_excel('new_students.xlsx')

更多 Pandas 讀取資料格式可以參考[官方文件](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html)

#### >>>回家練習：數值轉換，新增欄位，取值<<<

請先 restart kernel，接著直接執行以下程式，程式結果將下載 iris.csv 檔案

In [2]:
from urllib.request import urlretrieve
url = 'https://drive.google.com/uc?export=download&id=1DxOmm3dK2X0shq9h7XgyYI7FMi8OuUkv'
urlretrieve(url, "iris.csv")

('iris.csv', <http.client.HTTPMessage at 0x225fe2efd30>)

請使用 open( ) 讀取 iris.csv，請 print 出 '共有 ? 筆資料, ? 個欄位'

In [3]:
#your code
import pandas as pd

prt_list = []
hw_csv = pd.read_csv('iris.csv', header=None, encoding='utf-8')
for i in hw_csv.shape:
    prt_list.append(i)

print(f'共有{prt_list[0]}筆資料,{prt_list[1]}個欄位')

共有150筆資料,5個欄位


請使用 Pandas 讀取 iris.csv，將讀取到的 DataFrame 指派給變數 iris，並顯示前五筆資料

In [10]:
#your code
hw_csv.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

請問資料中共有幾筆遺漏值?

In [11]:
#your code
hw_csv.isnull().sum().sum()

4

請將遺漏值刪除，並 print 出 '刪除遺漏值後資料筆數為 ? 筆'

In [12]:
#your code
hw_csv = hw_csv.dropna()
print(f'刪除遺漏值後資料筆數為{len(hw_csv.values)}筆')

刪除遺漏值後資料筆數為146筆


請將資料新增四個欄位，分別為欄位一到欄位四的 dummy variable (小於欄位平均數為 0，大於等於欄位平均數為 1)
> 範例如下：

||0|1|2|3|4|5|6|7|8|
|-|-|-|-|-|-|-|-|-|-|
|0|5.1|3.5|1.4|0.2|Iris-setosa|0|1|0|0|
|1|4.9|3.0|1.4|0.2|Iris-setosa|0|0|0|0|


In [24]:
#your code
import numpy as np

hw_csv[5] = np.nan
hw_csv[6] = np.nan
hw_csv[7] = np.nan
hw_csv[8] = np.nan

avg_list = []

for avg in hw_csv.mean():
    avg_list.append(avg)

for i in range(len(hw_csv.values)):
    for j in range(4):
        if hw_csv.iloc[i,j] > avg_list[j]:
            hw_csv.iloc[i,j+5] = '1'
        else:
            hw_csv.iloc[i,j+5] = '0'

hw_csv




0    1    2    3               4  5  6  7  8
0    5.1  3.5  1.4  0.2     Iris-setosa  0  1  0  0
1    4.9  3.0  1.4  0.2     Iris-setosa  0  0  0  0
2    4.7  3.2  1.3  0.2     Iris-setosa  0  1  0  0
3    4.6  3.1  1.5  0.2     Iris-setosa  0  1  0  0
4    5.0  3.6  1.4  0.2     Iris-setosa  0  1  0  0
..   ...  ...  ...  ...             ... .. .. .. ..
145  6.7  3.0  5.2  2.3  Iris-virginica  1  0  1  1
146  6.3  2.5  5.0  1.9  Iris-virginica  1  0  1  1
147  6.5  3.0  5.2  2.0  Iris-virginica  1  0  1  1
148  6.2  3.4  5.4  2.3  Iris-virginica  1  1  1  1
149  5.9  3.0  5.1  1.8  Iris-virginica  1  0  1  1

[146 rows x 9 columns]

請將新增的四欄轉成 Numpy Array，並指派給變數 train_x

In [42]:
#your code
import numpy as np

hw_csv[5] = np.nan
hw_csv[6] = np.nan
hw_csv[7] = np.nan
hw_csv[8] = np.nan

avg_list = []

for avg in hw_csv.mean():
    avg_list.append(avg)

for i in range(len(hw_csv.values)):
    for j in range(4):
        if hw_csv.iloc[i,j] > avg_list[j]:
            hw_csv.iloc[i,j+5] = '1'
        else:
            hw_csv.iloc[i,j+5] = '0'

opt = pd.DataFrame(hw_csv[[5,6,7,8]]) 
train_x = opt.to_numpy()
train_x

array([['0', '1', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '0', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '1', '0', '0'],
       ['0', '

請再將資料新增一個欄位，把第五欄的資料的 Iris-setosa -> 0, Iris-versicolor-> 1, Iris-virginica -> 2

In [49]:
#your code
import numpy as np

hw_csv[5] = np.nan
hw_csv[6] = np.nan
hw_csv[7] = np.nan
hw_csv[8] = np.nan

avg_list = []

for avg in hw_csv.mean():
    avg_list.append(avg)

for i in range(len(hw_csv.values)):
    for j in range(4):
        if hw_csv.iloc[i,j] > avg_list[j]:
            hw_csv.iloc[i,j+5] = '1'
        else:
            hw_csv.iloc[i,j+5] = '0'

            
hw_csv['rename'] = np.nan

for i in range(len(hw_csv.values)):
    if hw_csv.iloc[i,4] == 'Iris-setosa':
        hw_csv.iloc[i,9] = '0'
    elif hw_csv.iloc[i,4] == 'Iris-versicolor':
        hw_csv.iloc[i,9] = '1'
    elif hw_csv.iloc[i,4] == 'Iris-virginica':
        hw_csv.iloc[i,9] = '2'   
        
hw_csv



0    1    2    3               4  5  6  7  8 rename
0    5.1  3.5  1.4  0.2     Iris-setosa  0  1  0  0      0
1    4.9  3.0  1.4  0.2     Iris-setosa  0  0  0  0      0
2    4.7  3.2  1.3  0.2     Iris-setosa  0  1  0  0      0
3    4.6  3.1  1.5  0.2     Iris-setosa  0  1  0  0      0
4    5.0  3.6  1.4  0.2     Iris-setosa  0  1  0  0      0
..   ...  ...  ...  ...             ... .. .. .. ..    ...
145  6.7  3.0  5.2  2.3  Iris-virginica  1  0  1  1      2
146  6.3  2.5  5.0  1.9  Iris-virginica  1  0  1  1      2
147  6.5  3.0  5.2  2.0  Iris-virginica  1  0  1  1      2
148  6.2  3.4  5.4  2.3  Iris-virginica  1  1  1  1      2
149  5.9  3.0  5.1  1.8  Iris-virginica  1  0  1  1      2

[146 rows x 10 columns]

請將新增的一欄轉成 Numpy Array，並指派給變數 train_y

In [50]:
#your code
import numpy as np

hw_csv[5] = np.nan
hw_csv[6] = np.nan
hw_csv[7] = np.nan
hw_csv[8] = np.nan

avg_list = []

for avg in hw_csv.mean():
    avg_list.append(avg)

for i in range(len(hw_csv.values)):
    for j in range(4):
        if hw_csv.iloc[i,j] > avg_list[j]:
            hw_csv.iloc[i,j+5] = '1'
        else:
            hw_csv.iloc[i,j+5] = '0'

            
hw_csv['rename'] = np.nan

for i in range(len(hw_csv.values)):
    if hw_csv.iloc[i,4] == 'Iris-setosa':
        hw_csv.iloc[i,9] = '0'
    elif hw_csv.iloc[i,4] == 'Iris-versicolor':
        hw_csv.iloc[i,9] = '1'
    elif hw_csv.iloc[i,4] == 'Iris-virginica':
        hw_csv.iloc[i,9] = '2'   

opt = pd.DataFrame(hw_csv['rename']) 
train_y = opt.to_numpy()
train_y




array([['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
      